# Generated by Django 6.0.2 on 2026-03-05 22:51

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('asset_type', models.CharField(choices=[('car', 'Voiture'), ('house', 'Maison'), ('land', 'Parcelle')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('desired_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=marketplace.models.upload_accessory_image)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['availability', 'price'], name='marketplace_availab_fda0a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=60)),
                ('model', models.CharField(db_index=True, max_length=60)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)])),
                ('mileage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['brand', 'model'], name='marketplace_brand_0f7346_idx'), models.Index(fields=['availability', 'price'], name='marketplace_availab_1ebb2d_idx'), models.Index(fields=['year', 'mileage'], name='marketplace_year_3f96bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.upload_car_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=60)),
                ('model', models.CharField(db_index=True, max_length=60)),
                ('storage', models.CharField(max_length=40)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['brand', 'model'], name='marketplace_brand_076681_idx'), models.Index(fields=['availability', 'price'], name='marketplace_availab_3b3028_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.upload_phone_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.phone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.upload_proposal_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_estate_type', models.CharField(choices=[('house', 'Maison'), ('land', 'Parcelle')], max_length=10)),
                ('location', models.CharField(db_index=True, max_length=140)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['real_estate_type', 'location'], name='marketplace_real_es_dbb38e_idx'), models.Index(fields=['availability', 'price'], name='marketplace_availab_268be1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.upload_real_estate_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.realestate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
