# Generated by Django 6.0.3 on 2026-03-06 01:18

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSellRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)])),
                ('desired_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarSellRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=marketplace.models.upload_sell_car_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Electrique'), ('gas', 'Gaz')], default='petrol', max_length=12),
        ),
        migrations.AddField(
            model_name='car',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='automatic', max_length=12),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Berline'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('van', 'Van'), ('other', 'Autre')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vehicle_type', 'availability'], name='marketplace_vehicle_c4973b_idx'),
        ),
        migrations.AddField(
            model_name='carsellrequestimage',
            name='sell_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.carsellrequest'),
        ),
    ]
