# Generated by Django 6.0.3 on 2026-03-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_carsellrequest_carsellrequestimage_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
