# Generated by Django 6.0.3 on 2026-03-06 14:12

from django.db import migrations, models
from django.utils.text import slugify


def _unique_slug(model, base_text, object_id):
    base_slug = slugify(base_text)[:170] or f"item-{object_id}"
    candidate = base_slug
    counter = 2
    while model.objects.filter(slug=candidate).exclude(pk=object_id).exists():
        suffix = f"-{counter}"
        candidate = f"{base_slug[:170 - len(suffix)]}{suffix}"
        counter += 1
    return candidate


def populate_slugs(apps, schema_editor):
    Car = apps.get_model('marketplace', 'Car')
    Phone = apps.get_model('marketplace', 'Phone')
    RealEstate = apps.get_model('marketplace', 'RealEstate')

    for car in Car.objects.all().iterator():
        if car.slug:
            continue
        car.slug = _unique_slug(Car, f"{car.brand} {car.model} {car.year}", car.pk)
        car.save(update_fields=['slug'])

    for phone in Phone.objects.all().iterator():
        if phone.slug:
            continue
        phone.slug = _unique_slug(Phone, f"{phone.brand} {phone.model}", phone.pk)
        phone.save(update_fields=['slug'])

    for listing in RealEstate.objects.all().iterator():
        if listing.slug:
            continue
        listing.slug = _unique_slug(RealEstate, f"{listing.real_estate_type} {listing.location}", listing.pk)
        listing.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_car_view_count_phone_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
