# Generated by Django 6.0.3 on 2026-03-06 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0006_create_agents_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('target_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMarketplaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, db_index=True, max_length=80)),
                ('notify_new_listings', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Baisse de prix'), ('new_listing', 'Nouvelle annonce')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['city', 'availability'], name='marketplace_city_8bdbbe_idx'),
        ),
        migrations.AddField(
            model_name='pricedropalert',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pricedropalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermarketplaceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pricedropalert',
            index=models.Index(fields=['content_type', 'object_id', 'is_active'], name='marketplace_content_813466_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricedropalert',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_price_alert'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='marketplace_user_id_d89aaf_idx'),
        ),
    ]
