# Generated by Django 6.0.3 on 2026-03-08 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_pricedropalert_usermarketplaceprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='proposal',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Electrique'), ('other', 'Autre')], max_length=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('new', 'Neuf'), ('used', 'Occasion'), ('refurbished', 'Reconditionne')], max_length=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='location_details',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='proposal',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='model_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='proposal',
            name='storage',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='surface_area',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='proposal',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manuelle'), ('automatic', 'Automatique'), ('other', 'Autre')], max_length=12),
        ),
        migrations.AddField(
            model_name='proposal',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='asset_type',
            field=models.CharField(choices=[('car', 'Voiture'), ('house', 'Maison'), ('land', 'Parcelle'), ('accessory', 'Accessoire'), ('phone', 'Telephone')], max_length=10),
        ),
    ]
