# Generated by Django 6.0.3 on 2026-03-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_proposal_brand_proposal_city_proposal_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12),
        ),
        migrations.AlterField(
            model_name='phone',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='availability',
            field=models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('reserved', 'Reserve'), ('sold', 'Vendu')], db_index=True, default='available', max_length=12),
        ),
    ]
