# Generated by Django 6.0.3 on 2026-03-24 20:45

import marketplace.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_accessory_stock_phone_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(db_index=True, max_length=160)),
                ("slug", models.SlugField(blank=True, db_index=True, max_length=180, null=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("prix", models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ("url_produit", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=160)),
                ("video", models.FileField(upload_to=marketplace.models.upload_product_video)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("produit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="marketplace.product")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
