# Generated by Django 6.0.3 on 2026-03-25 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_product_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-date_added'], 'verbose_name': 'Accessoire', 'verbose_name_plural': 'Accessoires'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-date_added'], 'verbose_name': 'Voiture', 'verbose_name_plural': 'Voitures'},
        ),
        migrations.AlterModelOptions(
            name='carsellrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de vente voiture', 'verbose_name_plural': 'Demandes de vente voiture'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-date_added'], 'verbose_name': 'Telephone', 'verbose_name_plural': 'Telephones'},
        ),
        migrations.AlterModelOptions(
            name='pricedropalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerte de baisse de prix', 'verbose_name_plural': 'Alertes de baisse de prix'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposition', 'verbose_name_plural': 'Propositions'},
        ),
        migrations.AlterModelOptions(
            name='realestate',
            options={'ordering': ['-date_added'], 'verbose_name': 'Bien immobilier', 'verbose_name_plural': 'Biens immobiliers'},
        ),
        migrations.AlterModelOptions(
            name='usermarketplaceprofile',
            options={'verbose_name': 'Profil marketplace', 'verbose_name_plural': 'Profils marketplace'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification utilisateur', 'verbose_name_plural': 'Notifications utilisateur'},
        ),
    ]
