# Generated by Django 6.0.3 on 2026-04-12 14:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('marketplace', '0012_alter_accessory_options_alter_car_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_commission',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_type', models.CharField(choices=[('individual', 'Particulier'), ('dealer', 'Dealer / Professionnel')], db_index=True, default='individual', max_length=12)),
                ('business_name', models.CharField(blank=True, max_length=120, verbose_name='Nom commercial')),
                ('phone', models.CharField(max_length=30, verbose_name='Telephone')),
                ('city', models.CharField(blank=True, db_index=True, max_length=80)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Verifie')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil vendeur',
                'verbose_name_plural': 'Profils vendeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='Reference')),
                ('buyer_name', models.CharField(blank=True, max_length=120, verbose_name='Nom acheteur')),
                ('buyer_phone', models.CharField(blank=True, max_length=30, verbose_name='Tel acheteur')),
                ('object_id', models.PositiveIntegerField()),
                ('item_title', models.CharField(max_length=200, verbose_name='Produit')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente')),
                ('payment_method', models.CharField(choices=[('cash', 'Especes'), ('mobile_money', 'Mobile Money'), ('bank', 'Virement bancaire'), ('other', 'Autre')], default='cash', max_length=16, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de vente')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='marketplace.sellerprofile', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accessory',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='marketplace.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='marketplace.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='phone',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='marketplace.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estates', to='marketplace.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(db_index=True, decimal_places=2, max_digits=5, verbose_name='Taux applique (%)')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, verbose_name='Montant commission')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payee'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=12, verbose_name='Statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='marketplace.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='marketplace_status_f048d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', 'created_at'], name='marketplace_seller__6ab214_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['content_type', 'object_id'], name='marketplace_content_a15d38_idx'),
        ),
    ]
