from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from .views import (
    AccessoryDetailView,
    AccessoryMarketplaceListView,
    AgentDashboardView,
    AgentLoginView,
    CarDetailView,
    CarMarketplaceListView,
    FavoritesView,
    PhoneDetailView,
    PhoneMarketplaceListView,
    SearchSuggestionsView,
    GlobalSearchView,
    SitemapXmlView,
    RobotsTxtView,
    GoogleSiteVerificationView,
    RegisterView,
    RealEstateDetailView,
    RealEstateMarketplaceListView,
    SellWithUsView,
    NotificationsView,
    TogglePriceAlertView,
    ToggleFavoriteView,
)

app_name = "marketplace"

urlpatterns = [
    re_path(r"^(?P<filename>google[a-zA-Z0-9]+\.html)$", GoogleSiteVerificationView.as_view(), name="google_site_verification"),
    path("connexion/", auth_views.LoginView.as_view(template_name="auth/login.html"), name="login"),
    path("inscription/", RegisterView.as_view(), name="register"),
    path("deconnexion/", auth_views.LogoutView.as_view(next_page="home"), name="logout"),
    path("agent/connexion/", AgentLoginView.as_view(), name="agent_login"),
    path("agent/espace/", AgentDashboardView.as_view(), name="agent_dashboard"),
    path("agent/deconnexion/", auth_views.LogoutView.as_view(next_page="home"), name="agent_logout"),
    path("sitemap.xml", SitemapXmlView.as_view(), name="sitemap_xml"),
    path("robots.txt", RobotsTxtView.as_view(), name="robots_txt"),
    path("recherche/", GlobalSearchView.as_view(), name="search"),
    path("recherche/suggestions/", SearchSuggestionsView.as_view(), name="search_suggestions"),
    path("voitures/", CarMarketplaceListView.as_view(), name="car_list"),
    path("voitures/<slug:slug>/", CarDetailView.as_view(), name="car_detail"),
    path("telephones/", PhoneMarketplaceListView.as_view(), name="phone_list"),
    path("telephones/<slug:slug>/", PhoneDetailView.as_view(), name="phone_detail"),
    path("accessoires/", AccessoryMarketplaceListView.as_view(), name="accessory_list"),
    path("accessoires/<int:pk>/", AccessoryDetailView.as_view(), name="accessory_detail"),
    path("immobilier/", RealEstateMarketplaceListView.as_view(), name="real_estate_list"),
    path("parcelles/", RealEstateMarketplaceListView.as_view(), name="land_list"),
    path("parcelles/<slug:slug>/", RealEstateDetailView.as_view(), name="land_detail"),
    path("immobilier/<slug:slug>/", RealEstateDetailView.as_view(), name="real_estate_detail"),
    path("vendre-avec-nous/", SellWithUsView.as_view(), name="sell_with_us"),
    path("favoris/", FavoritesView.as_view(), name="favorites"),
    path("favoris/toggle/<str:model_name>/<int:pk>/", ToggleFavoriteView.as_view(), name="toggle_favorite"),
    path("alertes/prix/<str:model_name>/<int:pk>/", TogglePriceAlertView.as_view(), name="toggle_price_alert"),
    path("notifications/", NotificationsView.as_view(), name="notifications"),
]
